name: 📦 Release
on:
  push:
    branches:
      - main
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'chore')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checkout the repo
        with:
          token: ${{ secrets.TOKEN }}
      - uses: actions/setup-node@v3 # setup node
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: git config --global user.email "${{ secrets.GIT_EMAIL }}" # setup git email
      - run: git config --global user.name "${{ secrets.GIT_NAME }}" # setup git name
      - name: Install dependencies
        run: npm ci # install dependencies
      - name: Build package and  update release
        run: npm run build -- -r # build
      - name: Publish package
        run: npm publish # publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Git push
        run: git push --follow-tags
