name: 📦 Release
on:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      main: github.ref == 'refs/heads/main'
      flag: ${{ github.ref == 'refs/heads/main' && '-r' || '-p'}}
      publishFlag:
        ${{ github.ref == 'refs/heads/dev' && '--tag develop' || '--tag develop'}}
    steps:
      - uses: actions/checkout@v2 # checkout the repo
      - uses: actions/setup-node@v3 # setup node
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: git config --global user.email "${{ secrets.GIT_EMAIL }}" # setup git email
      - run: git config --global user.name "${{ secrets.GIT_NAME }}" # setup git name
      - name: Install dependencies
        run: npm ci # install dependencies
      - name: Build package and  update release
        run: npm run build -- "$flag" # build
      - name: Publish package
        run: npm publish $publishFlag # publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Merge ci/release-action in dev2 branch
        if: ${{ env.main }}
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ci/release-action
          target_branch: dev2
          github_token: ${{ secrets.GITHUB_TOKEN }}
